### PR TITLE
Update bliss_strings.xml

### PR DESCRIPTION
**Pull request by razor84**
Add please

Thank you

### CODE REVIEW

**Comment by razor84** [comment]
Add please

Thank you

**Comment by ghost** [comment]
I have added all these string updates into a single gerrit commit, please push updates to our gerrit, will get them implemented much faster.

http://review.blissroms.com/#/c/635/

**Comment by razor84** [comment]
Hi,

Link does not work you have given

**Comment by razor84** [comment]
Merged please

**Comment by Meninblack007** [comment]
@razor84 http://review.blissroms.com/#/c/635/
Its merged :)

**Pull request closed without merging**
